### PR TITLE
bug #144: Suppress API error on 404

### LINKED ISSUE #144: bug: incorrect 404 error handling in resource `apstra_interface_map`
https://github.com/Juniper/terraform-provider-apstra/blob/bdf1341538cd2bf805df65fcb8c238edfedadb25/apstra/resource_interface_map.go#L313

https://github.com/Juniper/terraform-provider-apstra/blob/bdf1341538cd2bf805df65fcb8c238edfedadb25/apstra/resource_interface_map.go#L323

The `fetchEmbeddedObjects()` method returns multiple errors when it encounters a 404

### PR DESCRIPTION
**Pull request by chrismarget-j**
resource `apstra_interface_map` triggers multiple diagnostics when encountering a 404 while fetching device profile or logical device.

This PR ensures that only the "not found" or the API error is surfaced to the user and fixes #144.

### CODE REVIEW

File: apstra/resource_interface_map.go [hunk 1]
```diff
@@ -307,24 +307,27 @@ type rInterfaceMap struct {
...
 
 	// fetch the device profile specified by the user
 	dp, err := client.GetDeviceProfile(ctx, apstra.ObjectId(o.DeviceProfileId.ValueString()))
 	if err != nil {
 		if errors.As(err, &ace) && ace.Type() == apstra.ErrNotfound {
 			diags.AddAttributeError(path.Root("device_profile_id"), errInvalidConfig,
-				fmt.Sprintf("device profile '%s' not found", o.DeviceProfileId.ValueString()))
+				fmt.Sprintf("device profile %q not found", o.DeviceProfileId))
+		} else {
+			diags.AddError("error while fetching device profile", err.Error())
```
Comment (rajagopalans) [inline apstra/resource_interface_map.go:329]: How do we square the "error while..." pattern with the style guide reference about how summary for error should not start with error? I don't have an issue with it, personally, and have used it before.
Maybe the style guide can be amended.

**Review by rajagopalans — CHANGES_REQUESTED** [review]

File: apstra/resource_interface_map.go (hunk 1 above)
Comment (chrismarget-j) [reply apstra/resource_interface_map.go:329]: Just last week I noticed a user-facing error of the form "Error: error something something..." and thought: Well that seems silly, we should just print the reason for the error.

That facet of the style guide is a new idea. I'm trying to not write errors this way anymore.

Comment (chrismarget-j) [reply apstra/resource_interface_map.go:329]: lol. I didn't even read the error, nor did I notice what PR this was when I replied earlier. I just added the `else` wrapper.

You're absolutely right, and as the last one to touch this area I should clean that up.

Comment (chrismarget-j) [reply apstra/resource_interface_map.go]: d1a429c

**Review by rajagopalans — APPROVED** [review]

**Review by rajagopalans — APPROVED** [review]
